apiVersion: v1
kind: Pod
metadata:
  name: command-pod
spec:
  containers:
  - name: ubuntu-container
    image: ubuntu
    command: ["sleep"]
    args: ["10"] # command 를 대체한다. docker run --name ubuntu-container ubuntu 10
  