apiVersion: v1
kind: Service
metadata: 
  name: myapp-service
spec:
  type: NodePort # what service?
  ports:
  - targetPort: 80 # pod port
    port: 80 # service port
    nodePort: 30008 # node port / range: 30000-32767
  selector: # 연결할 pod label 정보
    app: myapp
    type: front-end