apiVersion: v1
kind: Pod
metadata:
  name: resource-limit-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:alpine
    resources:
      requests: 
        memory: "1Gi"
        cpu: 1
      limits:
        memory: "2Gi"
        cpu: 2
