apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  labels:
    name: secret-pod
spec:
  containers:
  - name: secret-pod
    image: ubuntu
    ports: 
      - containerPort: 8080
    envFrom:
      - secretRef:
          name: app-secret